/**
 * Executable schema generated by Grats (https://grats.capt.dev)
 * Do not manually edit. Regenerate by running `npx grats`.
 */

import { GraphQLSchema, GraphQLDirective, DirectiveLocation, GraphQLString, GraphQLBoolean, GraphQLList, GraphQLInt, specifiedDirectives, GraphQLObjectType, GraphQLNonNull, GraphQLInterfaceType, defaultFieldResolver, GraphQLID } from "graphql";
import { posts as userPostsResolver, allPosts as queryAllPostsResolver, forYou as queryForYouResolver, post as queryPostResolver, searchPosts as querySearchPostsResolver, createPost as mutationCreatePostResolver, upvotePost as mutationUpvotePostResolver, postUpvoteCountChanged as subscriptionPostUpvoteCountChangedResolver, author as imagePostAuthorResolver, comments as imagePostCommentsResolver, author as textPostAuthorResolver, comments as textPostCommentsResolver } from "./../Post";
import { User as queryMeResolver, User as queryUserResolver } from "./../User";
import { node as queryNodeResolver } from "./../node";
import { Comment as mutationAddCommentResolver } from "./../Comment";
import { sentimentAnalysis as imagePostSentimentAnalysisResolver, sentimentAnalysis as textPostSentimentAnalysisResolver } from "./../sentimentAnalysis";
async function assertNonNull<T>(value: T | Promise<T>): Promise<T> {
    const awaited = await value;
    if (awaited == null)
        throw new Error("Cannot return null for semantically non-nullable field.");
    return awaited;
}
export function getSchema(): GraphQLSchema {
    const NodeType: GraphQLInterfaceType = new GraphQLInterfaceType({
        name: "Node",
        fields() {
            return {
                id: {
                    name: "id",
                    type: new GraphQLNonNull(GraphQLID)
                }
            };
        }
    });
    const UserType: GraphQLObjectType = new GraphQLObjectType({
        name: "User",
        fields() {
            return {
                avatarColor: {
                    description: "A stable color derived from the user's ID, suitable for avatar backgrounds.",
                    name: "avatarColor",
                    type: GraphQLString,
                    resolve(source, args, context, info) {
                        return assertNonNull(defaultFieldResolver(source, args, context, info));
                    }
                },
                avatarUrl: {
                    name: "avatarUrl",
                    type: GraphQLString
                },
                id: {
                    name: "id",
                    type: new GraphQLNonNull(GraphQLID)
                },
                name: {
                    name: "name",
                    type: GraphQLString,
                    resolve(source, args, context, info) {
                        return assertNonNull(defaultFieldResolver(source, args, context, info));
                    }
                },
                posts: {
                    name: "posts",
                    type: new GraphQLList(new GraphQLNonNull(PostType)),
                    resolve(source) {
                        return assertNonNull(userPostsResolver(source));
                    }
                }
            };
        },
        interfaces() {
            return [NodeType];
        }
    });
    const CommentType: GraphQLObjectType = new GraphQLObjectType({
        name: "Comment",
        fields() {
            return {
                author: {
                    name: "author",
                    type: UserType,
                    resolve(source, args, context, info) {
                        return assertNonNull(defaultFieldResolver(source, args, context, info));
                    }
                },
                content: {
                    name: "content",
                    type: GraphQLString,
                    resolve(source, args, context, info) {
                        return assertNonNull(defaultFieldResolver(source, args, context, info));
                    }
                },
                createdAt: {
                    name: "createdAt",
                    type: GraphQLString,
                    resolve(source, args, context, info) {
                        return assertNonNull(defaultFieldResolver(source, args, context, info));
                    }
                },
                id: {
                    name: "id",
                    type: new GraphQLNonNull(GraphQLID)
                }
            };
        },
        interfaces() {
            return [NodeType];
        }
    });
    const CommentEdgeType: GraphQLObjectType = new GraphQLObjectType({
        name: "CommentEdge",
        fields() {
            return {
                cursor: {
                    name: "cursor",
                    type: new GraphQLNonNull(GraphQLString)
                },
                node: {
                    name: "node",
                    type: CommentType,
                    resolve(source, args, context, info) {
                        return assertNonNull(defaultFieldResolver(source, args, context, info));
                    }
                }
            };
        }
    });
    const PageInfoType: GraphQLObjectType = new GraphQLObjectType({
        name: "PageInfo",
        fields() {
            return {
                endCursor: {
                    name: "endCursor",
                    type: GraphQLString
                },
                hasNextPage: {
                    name: "hasNextPage",
                    type: new GraphQLNonNull(GraphQLBoolean)
                },
                hasPreviousPage: {
                    name: "hasPreviousPage",
                    type: new GraphQLNonNull(GraphQLBoolean)
                },
                startCursor: {
                    name: "startCursor",
                    type: GraphQLString
                }
            };
        }
    });
    const CommentConnectionType: GraphQLObjectType = new GraphQLObjectType({
        name: "CommentConnection",
        fields() {
            return {
                edges: {
                    name: "edges",
                    type: new GraphQLList(new GraphQLNonNull(CommentEdgeType)),
                    resolve(source, args, context, info) {
                        return assertNonNull(defaultFieldResolver(source, args, context, info));
                    }
                },
                pageInfo: {
                    name: "pageInfo",
                    type: new GraphQLNonNull(PageInfoType)
                },
                totalCount: {
                    name: "totalCount",
                    type: GraphQLInt
                }
            };
        }
    });
    const PostType: GraphQLInterfaceType = new GraphQLInterfaceType({
        name: "Post",
        fields() {
            return {
                author: {
                    name: "author",
                    type: UserType
                },
                comments: {
                    name: "comments",
                    type: CommentConnectionType
                },
                content: {
                    name: "content",
                    type: GraphQLString
                },
                createdAt: {
                    name: "createdAt",
                    type: GraphQLString
                },
                id: {
                    name: "id",
                    type: new GraphQLNonNull(GraphQLID)
                },
                sentimentAnalysis: {
                    description: "AI-generated analysis of the post's emotional tone.\nWarning: This field is slow (~4s). Clients should use defer to avoid blocking the rest of the response.",
                    name: "sentimentAnalysis",
                    type: GraphQLString
                },
                upvoteCount: {
                    name: "upvoteCount",
                    type: GraphQLInt
                }
            };
        },
        interfaces() {
            return [NodeType];
        }
    });
    const PostEdgeType: GraphQLObjectType = new GraphQLObjectType({
        name: "PostEdge",
        fields() {
            return {
                cursor: {
                    name: "cursor",
                    type: new GraphQLNonNull(GraphQLString)
                },
                node: {
                    name: "node",
                    type: PostType,
                    resolve(source, args, context, info) {
                        return assertNonNull(defaultFieldResolver(source, args, context, info));
                    }
                }
            };
        }
    });
    const PostConnectionType: GraphQLObjectType = new GraphQLObjectType({
        name: "PostConnection",
        fields() {
            return {
                edges: {
                    name: "edges",
                    type: new GraphQLList(new GraphQLNonNull(PostEdgeType)),
                    resolve(source, args, context, info) {
                        return assertNonNull(defaultFieldResolver(source, args, context, info));
                    }
                },
                pageInfo: {
                    name: "pageInfo",
                    type: new GraphQLNonNull(PageInfoType)
                },
                totalCount: {
                    name: "totalCount",
                    type: GraphQLInt
                }
            };
        }
    });
    const PostStreamableConnectionType: GraphQLObjectType = new GraphQLObjectType({
        name: "PostStreamableConnection",
        fields() {
            return {
                edges: {
                    name: "edges",
                    type: new GraphQLList(new GraphQLNonNull(PostEdgeType)),
                    resolve(source, args, context, info) {
                        return assertNonNull(defaultFieldResolver(source, args, context, info));
                    }
                },
                pageInfo: {
                    name: "pageInfo",
                    type: new GraphQLNonNull(PageInfoType)
                },
                totalCount: {
                    name: "totalCount",
                    type: GraphQLInt
                }
            };
        }
    });
    const QueryType: GraphQLObjectType = new GraphQLObjectType({
        name: "Query",
        fields() {
            return {
                allPosts: {
                    name: "allPosts",
                    type: PostConnectionType,
                    args: {
                        after: {
                            type: GraphQLString
                        },
                        before: {
                            type: GraphQLString
                        },
                        first: {
                            type: GraphQLInt
                        },
                        last: {
                            type: GraphQLInt
                        }
                    },
                    resolve(_source, args) {
                        return assertNonNull(queryAllPostsResolver(args.after, args.first, args.before, args.last));
                    }
                },
                forYou: {
                    description: "An algorithmically curated feed of posts. Results are ranked by a\ncomputationally expensive algorithm, so edges may resolve incrementally.\nClients can use `@stream` on the `edges` field to receive posts as\nthey become available rather than waiting for the full set.",
                    name: "forYou",
                    type: PostStreamableConnectionType,
                    args: {
                        after: {
                            type: GraphQLString
                        },
                        before: {
                            type: GraphQLString
                        },
                        first: {
                            type: GraphQLInt
                        },
                        last: {
                            type: GraphQLInt
                        }
                    },
                    resolve(_source, args) {
                        return assertNonNull(queryForYouResolver(args.after, args.first, args.before, args.last));
                    }
                },
                me: {
                    name: "me",
                    type: UserType,
                    resolve() {
                        return assertNonNull(queryMeResolver.me());
                    }
                },
                node: {
                    name: "node",
                    type: NodeType,
                    args: {
                        id: {
                            type: new GraphQLNonNull(GraphQLID)
                        }
                    },
                    resolve(_source, args) {
                        return queryNodeResolver(args.id);
                    }
                },
                post: {
                    name: "post",
                    type: PostType,
                    args: {
                        id: {
                            type: new GraphQLNonNull(GraphQLID)
                        }
                    },
                    resolve(_source, args) {
                        return queryPostResolver(args.id);
                    }
                },
                searchPosts: {
                    name: "searchPosts",
                    type: PostConnectionType,
                    args: {
                        after: {
                            type: GraphQLString
                        },
                        first: {
                            type: GraphQLInt
                        },
                        query: {
                            type: new GraphQLNonNull(GraphQLString)
                        }
                    },
                    resolve(_source, args) {
                        return assertNonNull(querySearchPostsResolver(args.query, args.after, args.first));
                    }
                },
                user: {
                    name: "user",
                    type: UserType,
                    args: {
                        id: {
                            type: new GraphQLNonNull(GraphQLID)
                        }
                    },
                    resolve(_source, args) {
                        return queryUserResolver.user(args.id);
                    }
                }
            };
        }
    });
    const AddCommentPayloadType: GraphQLObjectType = new GraphQLObjectType({
        name: "AddCommentPayload",
        fields() {
            return {
                comment: {
                    name: "comment",
                    type: CommentType
                },
                post: {
                    name: "post",
                    type: PostType
                }
            };
        }
    });
    const CreatePostPayloadType: GraphQLObjectType = new GraphQLObjectType({
        name: "CreatePostPayload",
        fields() {
            return {
                post: {
                    name: "post",
                    type: PostType
                }
            };
        }
    });
    const UpvotePostPayloadType: GraphQLObjectType = new GraphQLObjectType({
        name: "UpvotePostPayload",
        fields() {
            return {
                post: {
                    name: "post",
                    type: PostType
                }
            };
        }
    });
    const MutationType: GraphQLObjectType = new GraphQLObjectType({
        name: "Mutation",
        fields() {
            return {
                addComment: {
                    name: "addComment",
                    type: AddCommentPayloadType,
                    args: {
                        authorId: {
                            type: new GraphQLNonNull(GraphQLID)
                        },
                        content: {
                            type: new GraphQLNonNull(GraphQLString)
                        },
                        postId: {
                            type: new GraphQLNonNull(GraphQLID)
                        }
                    },
                    resolve(_source, args) {
                        return assertNonNull(mutationAddCommentResolver.addComment(args.postId, args.content, args.authorId));
                    }
                },
                createPost: {
                    name: "createPost",
                    type: CreatePostPayloadType,
                    args: {
                        authorId: {
                            type: new GraphQLNonNull(GraphQLID)
                        },
                        content: {
                            type: new GraphQLNonNull(GraphQLString)
                        },
                        imageAltText: {
                            type: GraphQLString
                        },
                        imageUrl: {
                            type: GraphQLString
                        }
                    },
                    resolve(_source, args) {
                        return assertNonNull(mutationCreatePostResolver(args.content, args.authorId, args.imageUrl, args.imageAltText));
                    }
                },
                upvotePost: {
                    name: "upvotePost",
                    type: UpvotePostPayloadType,
                    args: {
                        postId: {
                            type: new GraphQLNonNull(GraphQLID)
                        }
                    },
                    resolve(_source, args) {
                        return assertNonNull(mutationUpvotePostResolver(args.postId));
                    }
                }
            };
        }
    });
    const SubscriptionType: GraphQLObjectType = new GraphQLObjectType({
        name: "Subscription",
        fields() {
            return {
                postUpvoteCountChanged: {
                    name: "postUpvoteCountChanged",
                    type: PostType,
                    args: {
                        postId: {
                            type: new GraphQLNonNull(GraphQLID)
                        }
                    },
                    subscribe(_source, args) {
                        return subscriptionPostUpvoteCountChangedResolver(args.postId);
                    },
                    resolve(payload) {
                        return payload;
                    }
                }
            };
        }
    });
    const ImagePostType: GraphQLObjectType = new GraphQLObjectType({
        name: "ImagePost",
        fields() {
            return {
                author: {
                    name: "author",
                    type: UserType,
                    resolve(source) {
                        return assertNonNull(imagePostAuthorResolver(source));
                    }
                },
                comments: {
                    name: "comments",
                    type: CommentConnectionType,
                    resolve(source) {
                        return assertNonNull(imagePostCommentsResolver(source));
                    }
                },
                content: {
                    name: "content",
                    type: GraphQLString,
                    resolve(source, args, context, info) {
                        return assertNonNull(defaultFieldResolver(source, args, context, info));
                    }
                },
                createdAt: {
                    name: "createdAt",
                    type: GraphQLString,
                    resolve(source, args, context, info) {
                        return assertNonNull(defaultFieldResolver(source, args, context, info));
                    }
                },
                id: {
                    name: "id",
                    type: new GraphQLNonNull(GraphQLID)
                },
                imageAltText: {
                    name: "imageAltText",
                    type: GraphQLString
                },
                imageUrl: {
                    name: "imageUrl",
                    type: GraphQLString,
                    resolve(source, args, context, info) {
                        return assertNonNull(defaultFieldResolver(source, args, context, info));
                    }
                },
                sentimentAnalysis: {
                    description: "AI-generated analysis of the post's emotional tone.\nWarning: This field is slow (~4s). Clients should use defer to avoid blocking the rest of the response.",
                    name: "sentimentAnalysis",
                    type: GraphQLString,
                    resolve(source) {
                        return assertNonNull(imagePostSentimentAnalysisResolver(source));
                    }
                },
                upvoteCount: {
                    name: "upvoteCount",
                    type: GraphQLInt,
                    resolve(source, args, context, info) {
                        return assertNonNull(defaultFieldResolver(source, args, context, info));
                    }
                }
            };
        },
        interfaces() {
            return [NodeType, PostType];
        }
    });
    const TextPostType: GraphQLObjectType = new GraphQLObjectType({
        name: "TextPost",
        fields() {
            return {
                author: {
                    name: "author",
                    type: UserType,
                    resolve(source) {
                        return assertNonNull(textPostAuthorResolver(source));
                    }
                },
                comments: {
                    name: "comments",
                    type: CommentConnectionType,
                    resolve(source) {
                        return assertNonNull(textPostCommentsResolver(source));
                    }
                },
                content: {
                    name: "content",
                    type: GraphQLString,
                    resolve(source, args, context, info) {
                        return assertNonNull(defaultFieldResolver(source, args, context, info));
                    }
                },
                createdAt: {
                    name: "createdAt",
                    type: GraphQLString,
                    resolve(source, args, context, info) {
                        return assertNonNull(defaultFieldResolver(source, args, context, info));
                    }
                },
                id: {
                    name: "id",
                    type: new GraphQLNonNull(GraphQLID)
                },
                sentimentAnalysis: {
                    description: "AI-generated analysis of the post's emotional tone.\nWarning: This field is slow (~4s). Clients should use defer to avoid blocking the rest of the response.",
                    name: "sentimentAnalysis",
                    type: GraphQLString,
                    resolve(source) {
                        return assertNonNull(textPostSentimentAnalysisResolver(source));
                    }
                },
                upvoteCount: {
                    name: "upvoteCount",
                    type: GraphQLInt,
                    resolve(source, args, context, info) {
                        return assertNonNull(defaultFieldResolver(source, args, context, info));
                    }
                }
            };
        },
        interfaces() {
            return [NodeType, PostType];
        }
    });
    return new GraphQLSchema({
        directives: [...specifiedDirectives, new GraphQLDirective({
                name: "defer",
                locations: [DirectiveLocation.FRAGMENT_SPREAD, DirectiveLocation.INLINE_FRAGMENT],
                args: {
                    label: {
                        type: GraphQLString
                    },
                    if: {
                        type: GraphQLBoolean
                    }
                }
            }), new GraphQLDirective({
                name: "semanticNonNull",
                locations: [DirectiveLocation.FIELD_DEFINITION],
                description: "Indicates that a position is semantically non null: it is only null if there is a matching error in the `errors` array.\nIn all other cases, the position is non-null.\n\nTools doing code generation may use this information to generate the position as non-null if field errors are handled out of band:\n\n```graphql\ntype User {\n    # email is semantically non-null and can be generated as non-null by error-handling clients.\n    email: String @semanticNonNull\n}\n```\n\nThe `levels` argument indicates what levels are semantically non null in case of lists:\n\n```graphql\ntype User {\n    # friends is semantically non null\n    friends: [User] @semanticNonNull # same as @semanticNonNull(levels: [0])\n\n    # every friends[k] is semantically non null\n    friends: [User] @semanticNonNull(levels: [1])\n\n    # friends as well as every friends[k] is semantically non null\n    friends: [User] @semanticNonNull(levels: [0, 1])\n}\n```\n\n`levels` are zero indexed.\nPassing a negative level or a level greater than the list dimension is an error.",
                args: {
                    levels: {
                        type: new GraphQLList(GraphQLInt),
                        defaultValue: [0]
                    }
                }
            }), new GraphQLDirective({
                name: "stream",
                locations: [DirectiveLocation.FIELD],
                args: {
                    label: {
                        type: GraphQLString
                    },
                    initialCount: {
                        type: GraphQLInt
                    },
                    if: {
                        type: GraphQLBoolean
                    }
                }
            })],
        query: QueryType,
        mutation: MutationType,
        subscription: SubscriptionType,
        types: [NodeType, PostType, AddCommentPayloadType, CommentType, CommentConnectionType, CommentEdgeType, CreatePostPayloadType, ImagePostType, MutationType, PageInfoType, PostConnectionType, PostEdgeType, PostStreamableConnectionType, QueryType, SubscriptionType, TextPostType, UpvotePostPayloadType, UserType]
    });
}
